export { usersTable, userRelations } from "./tables/user/schema";
export { contactsTable, contactRelations } from "./tables/contact/schema";
export { addressesTable, addressRelations } from "./tables/address/schema";
export { clientsTable, clientRelations } from "./tables/client/schema";
export { suppliersTable, supplierRelations } from "./tables/supplier/schema";
export { projectsTable } from "./tables/project/schema";
export { itemsTable, itemRelations } from "./tables/item/schema";
export { projectItemsTable } from "./tables/project/schema";
export { documentsTable, documentRelations } from "./tables/document/schema";
export { documentRelationsTable, documentRelationsRelations } from "./tables/document/schema";
