import type { Template } from "@pdfme/common";
import { format } from "date-fns";
import { z } from "zod";

export const templateSchema = z.object({
  title: z.string().default("ACME INC"),
  companyName: z.string().default("ACME INC"),
  date: z.string().default(format(new Date(), "dd MMMM yyyy")),
  companyField: z
    .object({
      companyAddress: z.string(),
      companyCountry: z.string(),
      companyPhoneNmB: z.string(),
      companyPhoneNmA: z.string(),
      companyEmail: z.string(),
    })
    .default({
      companyAddress: "51 Rosetta st.",
      companyCountry: "Alexandria, Egypt",
      companyPhoneNmB: "+20 123 456 789",
      companyPhoneNmA: "+20 123 456 789",
      companyEmail: "info@acme-inc.com",
    })
    .transform((value) => JSON.stringify(value)),
  clientName: z.string(),
  clientField: z
    .object({
      clientAddress: z.string(),
      clientCountry: z.string(),
      clientPhoneNumber: z.string(),
      clientEmail: z.string(),
    })
    .transform((value) => JSON.stringify(value)),
  projectData: z
    .object({
      offerReference: z.string(),
      projectName: z.string(),
      projectManager: z.string(),
      ownerNumber: z.string().default("+20 123 456 789"),
      ownerEmail: z.string().default("sales@acme-inc.com"),
    })
    .transform((value) => JSON.stringify(value)),
  offerValidity: z
    .object({
      companyName: z.string(),
      offerValidityInDays: z.string(),
    })
    .default({ companyName: "ACME INC", offerValidityInDays: "7" })
    .transform((value) => JSON.stringify(value)),
  deliveryPeriod: z
    .object({
      deliveryPeriod: z.string(),
    })
    .default({ deliveryPeriod: "2 - 3 months" })
    .transform((value) => JSON.stringify(value)),
  items: z
    .array(
      z.object({
        name: z.string(),
        quantity: z.string(),
        price: z.string(),
        total: z.string(),
      }),
    )
    .transform((value) =>
      value.map((item) => [item.name, item.quantity, item.price, item.total]),
    ),
});

export const template: Template = {
  schemas: [
    [
      {
        name: "title",
        type: "text",
        position: { x: 20, y: 20 },
        required: true,
        content: "ACME INC",
        width: 120,
        height: 15,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 28,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        fontName: "readexProBold",
      },
      {
        name: "companyField",
        type: "multiVariableText",
        content:
          '{"companyAddress":"51 Rossetta st.","companyCountry":"Alexandria, Egypt","companyPhoneNmB":"+10001001","companyPhoneNmA":"+123123123","companyEmail":"info@acme.com"}',
        position: { x: 20, y: 50 },
        width: 70,
        height: 58,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.2,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "{companyAddress}\n{companyCountry}\n\n{companyPhoneNmA}\n{companyPhoneNmB}\n\n{companyEmail}",
        variables: [
          "companyAddress",
          "companyCountry",
          "companyPhoneNmA",
          "companyPhoneNmB",
          "companyEmail",
        ],
        required: true,
        fontName: "readexPro",
      },
      {
        name: "clientField",
        type: "multiVariableText",
        content:
          '{"clientAddress":"27 Syria street","clientCountry":"Alexandria, Egypt","clientPhoneNumber":"+20 123 456 7890","clientEmail":"purchasing@example.com\\n"}',
        position: { x: 120, y: 58 },
        width: 70,
        height: 50,
        rotate: 0,
        alignment: "right",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.2,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "{clientAddress}\n{clientCountry}\n\n{clientPhoneNumber}\n\n{clientEmail}",
        variables: [
          "clientAddress",
          "clientCountry",
          "clientPhoneNumber",
          "clientEmail",
        ],
        required: true,
        fontName: "readexPro",
      },
      {
        name: "projectKeys",
        type: "text",
        content: "Offer Reference\n\nProject Name\n\nProject Manager",
        position: { x: 30, y: 110 },
        width: 45,
        height: 40,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.2,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        fontName: "readexProBold",
        readOnly: true,
      },
      {
        name: "projectData",
        type: "multiVariableText",
        content:
          '{"offerReference":"P1CO20302","projectName":"Project 1","projectManager":"John Doe","ownerNumber":"+20 123 456 7890","ownerEmail":"johndoe@example.com"}',
        position: { x: 80, y: 110 },
        width: 49.21,
        height: 40,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.2,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "{offerReference}\n\n{projectName}\n\n{projectManager}\n{ownerNumber}\n{ownerEmail}",
        variables: [
          "offerReference",
          "projectName",
          "projectManager",
          "ownerNumber",
          "ownerEmail",
        ],
        required: true,
        fontName: "readexPro",
      },
      {
        name: "message",
        type: "text",
        content:
          "Dear Sir / Madam\n\n\tPlease Find enclosed here our quotation for the above mentioned subject. In case of any changes or comments you may require, please don’t hesitate to contact us.",
        position: { x: 20, y: 160 },
        width: 170,
        height: 30,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        fontName: "readexPro",
        readOnly: true,
      },
      {
        name: "subTitle",
        type: "text",
        content: "Commercial Offer",
        position: { x: 20, y: 35 },
        width: 45,
        height: 10,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#5a5a5a",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        readOnly: true,
        fontName: "readexPro",
      },
      {
        name: "clientName",
        type: "text",
        content: "Client",
        position: { x: 70, y: 50 },
        width: 120,
        height: 10,
        rotate: 0,
        alignment: "right",
        verticalAlignment: "top",
        fontSize: 15,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: true,
        readOnly: false,
        fontName: "readexProBold",
      },
      {
        name: "date",
        type: "text",
        content: "October 25, 2024",
        position: { x: 145, y: 25 },
        width: 45,
        height: 10,
        rotate: 0,
        alignment: "right",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: true,
        readOnly: false,
        fontName: "readexPro",
      },
      {
        name: "tocLabel",
        type: "text",
        content: "Table of Contents",
        position: { x: 20, y: 200 },
        width: 45,
        height: 10,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        readOnly: true,
        fontName: "readexProBold",
      },
      {
        name: "toc",
        type: "text",
        content: "1) Title Page\n2) General Conditions\n3) Offer Items",
        position: { x: 25, y: 210 },
        width: 100,
        height: 40,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.4,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        readOnly: true,
        fontName: "readexPro",
      },
    ],
    [
      {
        name: "conditionsLabel",
        type: "text",
        content: "General Conditions",
        position: { x: 20, y: 20 },
        width: 150,
        height: 15,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        readOnly: true,
        fontName: "readexProBold",
      },
      {
        name: "offerValidityLabel",
        type: "text",
        position: { x: 20, y: 40 },
        required: false,
        content: "1) Offer Validity",
        width: 45,
        height: 10,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 15,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        fontName: "readexProBold",
      },
      {
        name: "offerValidityKeys",
        type: "text",
        position: { x: 25, y: 50 },
        required: false,
        content: "For a period of\n\nStarting from",
        width: 35,
        height: 30,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
      },
      {
        name: "offerValidity",
        type: "multiVariableText",
        content: '{"companyName":"ACME INC","offerValidityInDays":"7"}',
        position: { x: 65, y: 50 },
        width: 120,
        height: 115,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.3,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "{offerValidityInDays} days\n\nOffer date\n\n- Should extension of validity be required beyond\nthe fixed period ({offerValidityInDays}) days, please contact us before the end of validity period to obtain a written extended validity period.\n\n- Beyond the fixed period of offer validity {companyName} is entitled to review / modify or cancel the prices and offers conditions.\n\n- In case of deterioration of EGP exchange rate\nversus the EUR/USD during the price list or offer\nvalidity period, then {companyName} has the right\nto reevaluate the price list or the offer to reflect\nsuch currency effect in the pricing.",
        variables: ["companyName", "offerValidityInDays"],
        required: true,
        fontName: "readexPro",
      },
      {
        name: "paymentLabel",
        type: "text",
        position: { x: 20, y: 165 },
        required: false,
        content: "2) Payment conditions",
        width: 65,
        height: 10,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 15,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        fontName: "readexProBold",
      },
      {
        name: "payment",
        type: "multiVariableText",
        content: "{}",
        position: { x: 25, y: 175 },
        width: 165,
        height: 25,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.8,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "( 25% ) advance payment from the total price by certified cheque or cash\n( 75% ) upon delivery through certified cheque or cash",
        variables: [],
        required: false,
        fontName: "readexPro",
      },
      {
        name: "taxesLabel",
        type: "text",
        position: { x: 20, y: 200 },
        required: false,
        content: "3) Taxes",
        width: 60,
        height: 10,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 15,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        fontName: "readexProBold",
      },
      {
        name: "taxes",
        type: "multiVariableText",
        content: "{}",
        position: { x: 25, y: 210 },
        width: 165,
        height: 15,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.8,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "This offer excludes the value added tax of (14%)",
        variables: [],
        required: false,
        fontName: "readexPro",
      },
      {
        name: "deliveryPeriodLabel",
        type: "text",
        position: { x: 20, y: 230 },
        required: false,
        content: "4) Delivery Period",
        width: 80,
        height: 10,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 15,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        fontName: "readexProBold",
      },
      {
        name: "deliveryPeriod",
        type: "multiVariableText",
        content: '{"deliveryPeriod":"2 - 3 months"}',
        position: { x: 25, y: 240 },
        width: 165,
        height: 20,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.8,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: false,
        text: "Delivery period is within {deliveryPeriod} from receiving the advance payment",
        variables: ["deliveryPeriod"],
        required: true,
        fontName: "readexPro",
      },
    ],
    [
      {
        type: "table",
        position: { x: 20, y: 40 },
        width: 170,
        height: 43.6424,
        content:
          '[["Eggshell Camisole Top","1","$123","$123"],["Cuban Collar Shirt","2","$127","$254"]]',
        showHead: true,
        head: ["Item", "Qty", "Unit Price", "Total"],
        headWidthPercentages: [40, 15, 20, 25],
        fontName: "readexPro",
        tableStyles: { borderWidth: 0, borderColor: "#000000" },
        headStyles: {
          fontName: "readexPro",
          fontSize: 13,
          characterSpacing: 0,
          alignment: "center",
          verticalAlignment: "middle",
          lineHeight: 1,
          fontColor: "#000000",
          borderColor: "#000000",
          backgroundColor: "",
          borderWidth: { top: 0, right: 0, bottom: 0, left: 0 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        bodyStyles: {
          fontName: "readexPro",
          fontSize: 10,
          characterSpacing: 0,
          alignment: "center",
          verticalAlignment: "middle",
          lineHeight: 1,
          fontColor: "#000000",
          borderColor: "#000000",
          backgroundColor: "",
          alternateBackgroundColor: "",
          borderWidth: { top: 0.1, right: 0, bottom: 0, left: 0 },
          padding: { top: 6, right: 5, bottom: 5, left: 5 },
        },
        columnStyles: {
          alignment: { "0": "left", "1": "center", "2": "right", "3": "right" },
        },
        name: "items",
        readOnly: false,
        required: true,
      },
      {
        name: "itemsLabel",
        type: "text",
        content: "Offer Items",
        position: { x: 20, y: 20 },
        width: 70,
        height: 15,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 20,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        readOnly: true,
        fontName: "readexProBold",
      },
    ],
  ],
  basePdf: { width: 210, height: 297, padding: [20, 20, 20, 20] },
  pdfmeVersion: "5.0.0",
};
