import type { Template } from "@pdfme/common";

export const template: Template = {
  schemas: [
    [
      {
        type: "svg",
        position: { x: 20, y: 20 },
        content:
          '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />\n</svg>\n',
        width: 23.86,
        height: 23.86,
        readOnly: true,
        name: "logo",
      },
      {
        type: "text",
        position: { x: 120.13, y: 20 },
        content: "INVOICE",
        width: 69.87,
        height: 22.68,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "middle",
        fontSize: 40,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "head",
      },
      {
        type: "text",
        position: { x: 20, y: 57.88 },
        content: "Billed to:",
        width: 84.69,
        height: 9.42,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "billedToLabel",
      },
      {
        type: "text",
        content:
          "Imani Olowe \n+123-456-7890 \n63 Ivy Road, Hawkville, GA, USA 31036",
        position: { x: 20, y: 67.94 },
        width: 84.95,
        height: 34.07,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        dynamicFontSize: { min: 3, max: 13, fit: "vertical" },
        // fontName: "amiri",
        name: "billedToInput",
      },
      {
        type: "multiVariableText",
        position: { x: 119.87, y: 67.88 },
        content: '{"InvoiceNo":"12345","Date":"16 June 2025"}',
        width: 70.13,
        height: 33.52,
        rotate: 0,
        alignment: "right",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1.5,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        text: "Invoice No.{InvoiceNo}\n{Date}",
        variables: ["InvoiceNo", "Date"],
        // fontName: "amiri",
        name: "info",
      },
      {
        type: "table",
        position: { x: 20, y: 110.81 },
        width: 170,
        height: 45.75920000000001,
        content:
          '[["Eggshell Camisole Top","1","$123","$123"],["Cuban Collar Shirt","2","$127","$254"]]',
        showHead: true,
        head: ["Item", "Qty", "Unit Price", "Total"],
        headWidthPercentages: [40, 15, 20, 25],
        // fontName: "amiri",
        tableStyles: { borderColor: "#000000", borderWidth: 0 },
        headStyles: {
          // fontName: "amiri",
          fontSize: 13,
          characterSpacing: 0,
          alignment: "center",
          verticalAlignment: "middle",
          lineHeight: 1,
          fontColor: "#000000",
          borderColor: "#000000",
          backgroundColor: "",
          borderWidth: { top: 0.1, right: 0, bottom: 0, left: 0 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        bodyStyles: {
          // fontName: "amiri",
          fontSize: 13,
          characterSpacing: 0,
          alignment: "center",
          verticalAlignment: "middle",
          lineHeight: 1,
          fontColor: "#000000",
          borderColor: "#000000",
          backgroundColor: "",
          alternateBackgroundColor: "",
          borderWidth: { top: 0.1, right: 0, bottom: 0.1, left: 0 },
          padding: { top: 6, right: 5, bottom: 5, left: 5 },
        },
        columnStyles: { alignment: { "0": "left", "3": "right" } },
        name: "orders",
      },
      {
        type: "text",
        position: { x: 138.01, y: 156.89 },
        content: "Subtotal",
        width: 25.42,
        height: 8.09,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "subtotalLabel",
      },
      {
        type: "text",
        position: { x: 138.01, y: 164.98 },
        content: "Tax (0%)",
        width: 25.42,
        height: 8.89,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "taxLabel",
      },
      {
        type: "line",
        position: { x: 137.09, y: 174.35 },
        width: 52.91,
        height: 0.1,
        rotate: 0,
        opacity: 1,
        readOnly: true,
        color: "#000000",
        name: "line",
      },
      {
        type: "text",
        content: "$500",
        position: { x: 163.79, y: 157.1 },
        width: 26.21,
        height: 7.56,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        // fontName: "amiri",
        name: "subtotalInput",
      },
      {
        type: "text",
        content: "$0",
        position: { x: 163.79, y: 164.98 },
        width: 26.21,
        height: 8.89,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        // fontName: "amiri",
        name: "taxInput",
      },
      {
        type: "text",
        position: { x: 136.94, y: 174.64 },
        content: "Total",
        width: 27.01,
        height: 11,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 20,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        // fontName: "amiri",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        name: "totalLabel",
      },
      {
        type: "text",
        content: "$500",
        position: { x: 164.05, y: 174.64 },
        width: 25.95,
        height: 11,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 20,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        // fontName: "amiri",
        name: "totalInput",
      },
      {
        type: "text",
        position: { x: 20, y: 191.58 },
        content: "Thank you!",
        width: 52.67,
        height: 20,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 20,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        // fontName: "amiri",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        name: "thankyou",
      },
      {
        type: "text",
        position: { x: 20, y: 232.67 },
        content: "Payment Information",
        width: 84.69,
        height: 9.42,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "paymentInfoLabel",
      },
      {
        type: "text",
        content:
          "Briard Bank\nAccount Name: Samira Hadid\nAccount No.: 123-456-7890\nPay by: 5 July 2025",
        position: { x: 20, y: 242.83 },
        width: 84.95,
        height: 34.07,
        rotate: 0,
        alignment: "left",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        dynamicFontSize: { min: 3, max: 13, fit: "vertical" },
        // fontName: "amiri",
        name: "paymentInfoInput",
      },
      {
        type: "text",
        position: { x: 119.33, y: 248.39 },
        content: "Samira Hadid",
        width: 70.67,
        height: 8.36,
        rotate: 0,
        alignment: "right",
        verticalAlignment: "top",
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "shopName",
      },
      {
        type: "text",
        position: { x: 107.69, y: 256.9 },
        content: "123 Anywhere St., Any City, ST 12345",
        width: 82.31,
        height: 20,
        rotate: 0,
        alignment: "right",
        verticalAlignment: "top",
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        backgroundColor: "",
        opacity: 1,
        readOnly: true,
        // fontName: "amiri",
        name: "shopAddress",
      },
    ],
  ],
  basePdf: { width: 210, height: 297, padding: [20, 20, 20, 20] },
  pdfmeVersion: "4.0.0",
};
